USE [master];
GO

CREATE MASTER KEY
	ENCRYPTION BY PASSWORD = 'Really Str0ng P@ssw0rd!'
;
GO

CREATE CERTIFICATE TdeServerCert01
	WITH
		SUBJECT = 'Database Encryption Key Cert'
;
GO

USE Adventureworks2019_TDE;
GO

CREATE DATABASE ENCRYPTION KEY
	WITH
		ALGORITHM = AES_256
	ENCRYPTION BY SERVER CERTIFICATE TdeServerCert01
;
GO

ALTER DATABASE Adventureworks2019_TDE
	SET ENCRYPTION ON
;
GO